[package]
name = "depura"
description = "simple logging, benchmarking, debugging"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.1" # sync with readme, check.sh & .github/workflows/check.yml
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/depura"
documentation = "https://docs.rs/depura"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/README.md",
	"/LICENSE-*",
]
categories = ["development-tools::debugging", "development-tools::profiling"]
keywords = []
publish = true

[features]
default = ["std", "safe"]

std = ["alloc", "log/std", "instant", "simplelog", "time/local-offset", "time/formatting", "human-repr"]
alloc = []
no-std = []

safe = []
unsafe = []

nightly = [] # used only for documentation


[dependencies]
log = "0.4"
time = { version = "0.3.22", default-features = false }

#* optional *#

human-repr = { version = "1.1.0", optional = true }
instant = { version = "0.1.12", optional = true, features = [ "wasm-bindgen", "inaccurate" ] }
simplelog = { version = "0.12.1", optional = true, default-features = false, features = ["local-offset"] }

[dev-dependencies]


[package.metadata.docs.rs]
no-default-features = true
features = ["nightly", "std"]

[badges]
maintenance = { status = "experimental" }
