[package]
name = "depura"
description = "simple logging, benchmarking, debugging"
version = "0.0.2"
edition = "2021"
resolver = "2"
rust-version = "1.63.0" # limited by: time-macros
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/depura"
documentation = "https://docs.rs/depura"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/README.md",
	"/LICENSE-*",
]
categories = ["development-tools::debugging"]
keywords = []
publish = true

[dependencies]
log = "0.4"
simplelog = { version = "0.12.0", optional = true, default-features = false, features = ["local-offset"] }

human-repr = { version = "1.0.1", optional = true }
instant = { version = "0.1.12", optional = true, features = [ "wasm-bindgen", "inaccurate" ] }
time = { version = "0.3.20", default-features = false }

[features]
default = ["std", "safe"]
std = ["log/std", "instant", "simplelog", "time/local-offset", "time/formatting", "human-repr"]
safe = []
nightly = [] # used only for documentation

[dev-dependencies]

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = "nightly"
